# Generated by Django 5.2.4 on 2025-07-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('colors', models.ManyToManyField(related_name='flowers', to='flowershop.color')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerArrangementFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershop.flower')),
                ('flowerArrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershop.flowerarrangement')),
            ],
        ),
        migrations.AddField(
            model_name='flowerarrangement',
            name='flowers',
            field=models.ManyToManyField(related_name='arrangements', through='flowershop.FlowerArrangementFlower', to='flowershop.flower'),
        ),
    ]
