# Generated by Django 5.2.4 on 2025-07-13 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(default='kwiat', error_messages={'unique': 'Taki kwiat już istnieje w bazie danych.'}, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowerarrangement',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='FlowerArrangementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arrngement_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flowershop.flowerarrangement')),
            ],
        ),
    ]
