# Generated by Django 5.2.4 on 2025-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0002_alter_flower_name_alter_flowerarrangement_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerarrangementimage',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='arrangement_images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='flowerarrangement',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flowerarrangementflower',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
